version: '3'

services:
  nginx_pabellon:
    image: nginx:latest
    container_name: nginx_pabellon
    volumes:
      - ./pabellonScheduler:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web_pabellon
    ports:
      - "8086:80"

  web_pabellon:
    image: caracena/pabellon-scheduler
    container_name: web_pabellon
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn pabellonScheduler.wsgi -b 0.0.0.0:8000 --workers 3"
    volumes:
      - ./pabellonScheduler:/src
    expose:
      - "8000"
    links:
      - db_pabellon:db_pabellon

  db_pabellon:
    image: mariadb:latest
    container_name: db_pabellon
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: HLCMr00t
      MYSQL_DATABASE: pabellonScheduler
      MYSQL_USER: hlcmPabellonuser
      MYSQL_PASSWORD: hlcmPabellonDBus3r
    volumes:
      - ./data:/var/lib/mysql

networks:
  default:
    external:
      name: webproxy
