# Generated by Django 2.0 on 2019-07-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('ndays', models.IntegerField(null=True)),
                ('nrooms', models.IntegerField(null=True)),
                ('hoursam', models.IntegerField(null=True)),
                ('hourspm', models.IntegerField(null=True)),
            ],
        ),
    ]
