# Generated by Django 2.0 on 2019-07-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=15, null=True)),
                ('id_intervencion', models.CharField(max_length=100, null=True)),
                ('prestacion', models.CharField(max_length=15, null=True)),
                ('especialidad', models.CharField(max_length=100, null=True)),
                ('fechaingreso', models.DateField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.FileUpload')),
            ],
        ),
    ]
