# Generated by Django 2.0 on 2019-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tiempoespera',
            field=models.IntegerField(null=True),
        ),
    ]
