# Generated by Django 2.0 on 2019-07-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='schedule',
            field=models.ManyToManyField(to='dashboard.Schedule'),
        ),
    ]
