# Generated by Django 2.0 on 2019-07-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_ingreso_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='remaining_duration',
            field=models.IntegerField(null=True),
        ),
    ]
