# Generated by Django 2.0 on 2019-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_schedule_remaining_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='initial_duration',
            field=models.IntegerField(null=True),
        ),
    ]
