# Generated by Django 2.0 on 2019-07-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_schedule_initial_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
    ]
