# Generated by Django 2.0 on 2019-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_ingreso_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='prioridad',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
